class ProtocolError(Exception):
	pass

class AuthError(Exception):
	pass